export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

export const APPLICATION_START = 'APPLICATION_START';
export const APPLICATION_SUCCESS = 'APPLICATION_SUCCESS';
export const APPLICATION_FAILURE = 'APPLICATION_FAILURE';